import "@fontsource/geist-mono";
import "@fontsource/geist-sans";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
	title: "Next.js | Panda| Biome.js template",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className="antialiased">{children}</body>
		</html>
	);
}
